apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviesite-app
  labels:
    app: moviesite-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moviesite-app
  template:
    metadata:
      labels:
        app: moviesite-app
    spec:
      containers:
      - name: moviesite-app
        image: achchuptk/moviesite:latest
        ports:
        - containerPort: 80
