apiVersion: v1
kind: Service
metadata:
  name: moviesite-app
  labels:
    app: moviesite-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: moviesite-app
